Normalize=function(team_data)
{
  normalize.z=function(varailbe)
  {
    m=mean(varailbe)
    s=sd(varailbe)
    z.x=(varailbe-m)/s
  }
  team_data$z.missFG <- with(team_data, normalize.z(team_data$missFG))
  team_data$z.missFT <- with(team_data, normalize.z(team_data$missFT))
  team_data$z.FG <- with(team_data, normalize.z(team_data$FG))
  team_data$z.FGA <- with(team_data, normalize.z(team_data$FGA))
  team_data$z.X3P <- with(team_data, normalize.z(team_data$X3P))
  team_data$z.X3PA <- with(team_data, normalize.z(team_data$X3PA))
  team_data$z.FT <- with(team_data, normalize.z(team_data$FT))
  team_data$z.FTA <- with(team_data, normalize.z(team_data$FTA))
  team_data$z.ORB <- with(team_data, normalize.z(team_data$ORB))
  team_data$z.DRB <- with(team_data, normalize.z(team_data$DRB))
  team_data$z.TRB <- with(team_data, normalize.z(team_data$TRB))
  team_data$z.AST <- with(team_data, normalize.z(team_data$AST))
  team_data$z.STL <- with(team_data, normalize.z(team_data$STL))
  team_data$z.BLK <- with(team_data, normalize.z(team_data$BLK))
  team_data$z.TOV <- with(team_data, normalize.z(team_data$TOV))
  team_data$z.PF <- with(team_data, normalize.z(team_data$PF))
  team_data$z.missOpp.FG<-with(team_data, normalize.z(team_data$missOpp.FG))
  team_data$z.missOpp.FT<-with(team_data, normalize.z(team_data$missOpp.FT))
  team_data$z.Opp.FG <- with(team_data, normalize.z(team_data$Opp.FG))
  team_data$z.Opp.FGA <- with(team_data, normalize.z(team_data$Opp.FGA))
  team_data$z.Opp.3P <- with(team_data, normalize.z(team_data$Opp.3P))
  team_data$z.Opp.3PA <- with(team_data, normalize.z(team_data$Opp.3PA))
  team_data$z.Opp.FT <- with(team_data, normalize.z(team_data$Opp.FT))
  team_data$z.Opp.FTA <- with(team_data, normalize.z(team_data$Opp.FTA))
  team_data$z.Opp.ORB <- with(team_data, normalize.z(team_data$Opp.ORB))
  team_data$z.Opp.DRB <- with(team_data, normalize.z(team_data$Opp.DRB))
  team_data$z.Opp.TRB <- with(team_data, normalize.z(team_data$Opp.TRB))
  team_data$z.Opp.AST <- with(team_data, normalize.z(team_data$Opp.AST))
  team_data$z.Opp.STL <- with(team_data, normalize.z(team_data$Opp.STL))
  team_data$z.Opp.BLK <- with(team_data, normalize.z(team_data$Opp.BLK))
  team_data$z.Opp.TOV <- with(team_data, normalize.z(team_data$Opp.TOV))
  team_data$z.Opp.PF <- with(team_data, normalize.z(team_data$Opp.PF))
  return(team_data)
}
