Advanced_Statistic=function(team_data)
{
  team_data$missFG  <-  with(team_data, FGA-FG)
  team_data$missOpp.FG  <-  with(team_data, Opp.FGA-Opp.FG)
  team_data$missFT <- with(team_data, FTA-FT)
  team_data$missOpp.FT <- with(team_data, Opp.FTA-Opp.FT)
  team_data$DRB <- with(team_data, TRB-ORB)
  team_data$Opp.DRB <- with(team_data, Opp.TRB-Opp.ORB)
  team_data$FG. <- with(team_data, FG/FGA)
  team_data$TFG. <- with(team_data, X3P/X3PA)
  team_data$FT. <- with(team_data, FT/FTA)
  #team_data$Opp.FG. <- with(team_data, Opp.FG/Opp.FGA)
  #team_data$Opp.TFG. <- with(team_data, Opp.3P/Opp.3PA)
  #team_data$Opp.FT. <- with(team_data, Opp.FT/Opp.FTA)
  team_data$Poss <- with(team_data, FGA-(ORB/(ORB+(Opp.TRB-Opp.ORB)))*(FGA-FG)*1.07+TOV+0.4*FTA)
  team_data$Opp.Poss <- with(team_data, Opp.FGA-(Opp.ORB/(Opp.ORB+(TRB-ORB)))*(Opp.FGA-Opp.FG)*1.07+Opp.TOV+0.4*Opp.FTA)
  team_data$EFGP <-  with(team_data, (FG+0.5*X3P)/FGA)
  team_data$Opp.EFGP <-  with(team_data, (Opp.FG+0.5*Opp.3P)/Opp.FGA)
  team_data$TOVP <-  with(team_data, TOV/(FGA+0.44*FTA+TOV))
  team_data$Opp.TOVP <-  with(team_data, Opp.TOV/(Opp.FGA+0.44*Opp.FTA+Opp.TOV))
  team_data$ORBP <-  with(team_data, ORB/(ORB+(Opp.TRB-Opp.ORB)))
  team_data$DRBP <-  with(team_data, (TRB-ORB)/(Opp.ORB+(TRB-ORB)))
  team_data$FTR <-  with(team_data, FT/FGA)
  team_data$Opp.FTR <-  with(team_data, Opp.FT/Opp.FGA)
  team_data$diffEFG <- with(team_data, EFGP-Opp.EFGP)
  team_data$diffTOV <- with(team_data, TOVP-Opp.TOVP)
  team_data$diffRB <- with(team_data, ORBP-DRBP)
  team_data$diffFTR <- with(team_data, FTR-Opp.FTR)
  team_data$ORtg <- with(team_data, (PTS/Poss)*100)
  team_data$DRtg <- with(team_data, (Opp.PTS/Opp.Poss)*100)
  team_data$S.Poss <- with(team_data, FGA+(1-(1-FT.)^2)*FTA*0.4)
  team_data$Opp.S.Poss <- with(team_data, Opp.FGA+(1-(1-Opp.FTP)^2)*Opp.FTA*0.4)
  team_data$TSP <- with(team_data, PTS/(2*(FGA+0.44*FTA)))
  team_data$Opp.TSP <- with(team_data, Opp.PTS/(2*(Opp.FGA+0.44*Opp.FTA)))
  return(team_data)
}